name: API test with Newman

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman
          #npm install -g newman-reporter-html-extra

      - name: Run collection
        run: |
          newman run postman_collection.json -e postman_environment.json --reporters cli

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip
          
